version: '3.9'

services:
  web:
    build: .
    container_name: learncloud_web
    command: ./entrypoint.sh
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/learncloud
    volumes:
      - static_volume:/app/static/

  db:
    image: postgres:15
    container_name: learncloud_db
    environment:
      POSTGRES_DB: learncloud
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
  static_volume:
